### ISSUE TITLE
Deleting a category poses problem to Products migration

### ISSUE THREAD

**Issue by muarachmann** [lehone-hp/furnish#16]
@lehone-hp the delete functionality has been integrated in #15 . This has a short coming cause if you delete a category then in category_id field of the products table, we must have a null value. According to your constraints this is not possible.

1. Either we change that to a null and Products automatically will not be categorised if the category is being deleted 

2. We prevent cats from being deleted at all

Your thoughts on this

**Comment by lehone-hp** [comment]
I have fixed the issue
