### ISSUE TITLE
Grid View swap to List view not displaying correctly.

### ISSUE THREAD

**Issue by muarachmann** [lehone-hp/furnish#20]
I just got the latest codes @lehone-hp and noticed when you change from grid view to list view it still shows static contents of the template site. Can you check this out

**Comment by muarachmann** [comment]
### GRID VIEW
![screen shot 2018-12-19 at 8 06 11 am](https://user-images.githubusercontent.com/16350814/50204412-04e1d500-0365-11e9-8076-929916b25887.png)

### LIST VIEW
![screen shot 2018-12-19 at 8 06 19 am](https://user-images.githubusercontent.com/16350814/50204435-19be6880-0365-11e9-8e97-fd529029da55.png)

**Comment by lehone-hp** [comment]
Fixed the List View problem and did some few restructuring. Checkout the [PR](https://github.com/lehone-hp/furnish/pull/22)

**Comment by lehone-hp** [comment]
For the shop section what I can say is left is the price filter and the pagination but for now I want us to move on with the adding items to cart -> checkout workflow.

**Comment by muarachmann** [comment]
ok then
