### ISSUE TITLE
Database Modelling for furnish 

### ISSUE THREAD

**Issue by muarachmann** [lehone-hp/furnish#8]
@lehone-hp opening this thread for discussions of the schema you pulled up

**Comment by lehone-hp** [comment]
Okay cool

**Comment by muarachmann** [comment]
Okay in the original theme i see products can have several images and also what is minorder for?

**Comment by lehone-hp** [comment]
minorder if for the minimum amount of a product which can be ordered

**Comment by muarachmann** [comment]
That can be hardcoded in the increase and decrease buttons up in the front end. Using either html or js

**Comment by lehone-hp** [comment]
> That can be hardcoded in the increase and decrease buttons up in the front end. Using either html or js

I want the admin to be able to specify different min order for different products

**Comment by muarachmann** [comment]
Okay i that direction ok. And what is quantity. Is it like in stock out of stock kind of thing?

**Comment by muarachmann** [comment]
Also `is_parent` & `parent_id` ? whats that for. categories of categories. I dont get

**Comment by lehone-hp** [comment]
> Also `is_parent` & `parent_id` ? whats that for. categories of categories. I dont get

I was thinking that we could have parent categories and children categories where the `is_parent ` identifies a category as a parent and a category that's a child uses the `parent_id` to reference the parent category
but we can remove this and have just one level, what do you think.

**Comment by muarachmann** [comment]
Yep we can remove this. What we could do is like a blog post has categories and has tags. Something of the sort.... A product has a main category and if you want to like bring sub categories lets use the idea of tags here.... If not we could just use on category for them. Looking at the shop template of furnish i see it there

![screen shot 2018-12-08 at 3 49 03 pm](https://user-images.githubusercontent.com/16350814/49687324-a6655d00-fb01-11e8-94fb-2a870c9cccad.png)

**Comment by lehone-hp** [comment]
No tags for now, we will do just the single category then. Keeping it simple
Lucky for us the client didn't require all that.
I will comment out that POPULAR TAG section

**Comment by muarachmann** [comment]
Hahahahaha okay then one cat will do then. The others are Ok. How far with the client section?

**Comment by lehone-hp** [comment]
Cool. I wanted us to agree on the data model before I can continues

**Comment by muarachmann** [comment]
One thing. Place availability of product too. Like instock -- bool

**Comment by lehone-hp** [comment]
okay.
So should I proceed with creating the migations or u wanna do that?

**Comment by muarachmann** [comment]
nope created them i will follow suite

**Comment by muarachmann** [comment]
Product, Category, Order should be the model. If you can do eloquesnt relationships in them fine. If not i will do them

**Comment by lehone-hp** [comment]
so it means our category table will now havve just name and id right?

**Comment by muarachmann** [comment]
> so it means our category table will now havve just name and id right?

Yep just that.

**Comment by lehone-hp** [comment]
> Product, Category, Order should be the model. If you can do eloquent relationships in them fine. If not i will do them.
> 
> Like in Product => `$this->belongsTo('App\Category')`

Yeah, I can do the relationships

**Comment by muarachmann** [comment]
Okay then great i will be waiting for that to continue. Let me take a break off. Thanks for your replies

**Comment by lehone-hp** [comment]
Ma finish United their match :-)

**Comment by muarachmann** [comment]
Closing this issue. Feel free to open another if any come up again in the futuree
